### ISSUE TITLE
배틀 화면

### ISSUE THREAD

**Issue by koipkoi** [koipkoi/pokeemerald-kr#1]
### 수정 목록
- [x] 배틀 메뉴 좁은폭 폰트로 교체
- [x] "와", "과" 구분이 뒤바뀌는 문제 수정
- [ ] HP, LV 등 폰트 스타일 교체
- [x] 기술 사용시 기술별 메시지 문법 구분 기능 수정
- [x] 조사 미출력 버그

**Comment by poketony** [comment]
배틀 공격 시 텍스트가 3개로 나누어지는데, src/battle_message.c의 425행이 
{B_ATK_NAME_WITH_PREFIX}{B_BUFF1}\n{B_BUFF2} 로 적혀야 제 기능을 합니다. 
다만 왜인지는 모르겠는데 ~를 썼다! 라고 출력되는 기술을 쓸 때 프리징 현상이 발생합니다. 
![pokeemerald_01](https://user-images.githubusercontent.com/57011422/104906506-2344af80-59c7-11eb-90ea-657f603f052d.png)
![pokeemerald_02](https://user-images.githubusercontent.com/57011422/104906519-28a1fa00-59c7-11eb-8ce7-5b7e914a269a.png)
![pokeemerald_03](https://user-images.githubusercontent.com/57011422/104906528-2a6bbd80-59c7-11eb-9728-668fc696e91a.png)

**Comment by koipkoi** [comment]
![KakaoTalk_20210214_161200577](https://user-images.githubusercontent.com/39587773/107870879-e396b800-6edf-11eb-84d2-b626bb6cbc26.png)
![KakaoTalk_20210214_161201769](https://user-images.githubusercontent.com/39587773/107870880-e4c7e500-6edf-11eb-8713-bab7d5738a0c.png)
조사 출력이 안됨

**Comment by poketony** [comment]
폰트 스타일은 그냥 이대로 놔둬도 괜찮을 것 같습니다. 파레/리그도 마찬가지인 상황이라 셋 다 바꾸거나 셋 다 이대로 놔두거나 해야 할 것 같네요. 원하는 방향으로 처리해 주세요!

**Comment by koipkoi** [comment]
@poketony HP도 설명해주신것처럼 처리할까요?
