### ISSUE TITLE
예/아니오 텍스트 창 에러

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-kr#12]
![error1](https://user-images.githubusercontent.com/57011422/109419473-f9909680-7a10-11eb-98cb-87c40b7abded.png)

제목 그대로입니다! 

포켓몬 교체 시나 포획 시 오류가 뜹니다.

**Comment by koipkoi** [comment]
@poketony 폰트를 바꾸는게 좋을까요? 아니면 창 너비를 늘리는게 좋을까요?
