### ISSUE TITLE
작은 폰트로 교체

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-kr#15]
![pokeemerald-3](https://user-images.githubusercontent.com/57011422/174525206-7561f9a1-a48a-4880-aef9-ec4e0aec7ae7.png)
![pokeemerald-4](https://user-images.githubusercontent.com/57011422/174525213-d6d82a24-5177-48fc-bf51-c9280ddf038f.png)

주인공 집 2층에 있는 PC에 뭔가를 맡길 때의 화면인데 도구 설명에 따라서 짤리는 경우가 있네요. 두 화면 다 작은 폰트로 교체해야 할 것 같습니다. 

그리고 추가로 여쭤보는 건데 현재 기본 폰트를 10pt에서 8x16 폰트로 변경해 주실 수 있나요? 아무래도 원본과 폰트 사이즈가 다른지라 이곳저곳에서 문제가 많이 일어나는 것 같습니다. 

커서 맞지 않는 경우를 일일이 찾아다녀서 10pt를 8x16으로 바꾸는 것보단,  
대부분의 화면의 디폴트 폰트값을 8x16으로 설정해 놓고, 10pt로 바꾸면 좋겠다 싶은 것들만 바꾸는 게 더 효율적일 것 같아서 여쭤봅니다

**Comment by koipkoi** [comment]
@poketony 반대의 경우로 10pt로 바꿔줘야하는 경우가 많지 않다면 괜찮은 방법이긴한데 걱정이 많이 되는 부분입니다.

여러군데의 화면에서 어울리지 않는 문제가 생길수 있을것 같아요.

**Comment by poketony** [comment]
@koipkoi 그래도 깨지는 것보단 어울리지 않는 게 더 낫다고 생각하고 
이곳저곳 플레이하다 보면 언젠가 다 메꿀 수 있을 거라고 생각해요

**Comment by koipkoi** [comment]
@poketony 브랜치를 따로 나눠서 작업하겠습니다. ([font-swap-dev](https://github.com/koipkoi/pokeemerald-kr/tree/font-swap-dev))

**Comment by koipkoi** [comment]
@poketony PR (#20) 기준으로 10pt 폰트는 이제 옵션으로 주어야합니다. 필요한 부분은 이슈 대신에 PR에 남겨주세요.
