### ISSUE TITLE
박스 메뉴에서 조사 누락 및 폰트 교체

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-kr#16]
![pokeemerald-6](https://user-images.githubusercontent.com/57011422/174527881-f89b1687-a009-4930-954d-5e5035638f90.png)
![화면 캡처 2022-06-20 135550](https://user-images.githubusercontent.com/57011422/174527945-47105a77-acfc-4ec5-9d23-bf03ca270cd2.png)

여태까지 에메랄드에선 일본 이름만 가진 포켓몬만 써서 눈치를 못 채고 있었는데, 박스 메뉴에서 조사 코드가 전혀 작동하고 있질 않더라구요 그리고 추가로 박스 메뉴에서 출력되는 폰트를 8x16으로 바꿔야 할 것 같습니다

**Comment by koipkoi** [comment]
제가 PR (#20) 부분에 따로 남기도록 하겠습니다.
