### ISSUE TITLE
통신 오류 메시지 줄 개행

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-kr#17]
![pokeemerald-0](https://user-images.githubusercontent.com/57011422/178354199-56f3345f-dc66-4b49-a21c-f934b50f489a.png)

**Comment by koipkoi** [comment]
@poketony 정상적으로 맞춰진 참고될만한 스크린샷이 있을까요?

**Comment by poketony** [comment]
![에메랄드 통신에러 줄맞춤](https://user-images.githubusercontent.com/57011422/179336298-747c693f-f336-4a58-b6e1-4d545e9849ac.png)

포토샵으로 줄 맞춰 봤습니다. 
참고로 현재 스크립트에는 '켜주십시오' 로 되어 있을 텐데 그 부분은 켜 주십시오로 다시 바꿔 주시면 감사하겠습니다
