### ISSUE TITLE
메뉴창 사이즈 롤백

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-kr#21]
![5  POKEMON_EMER_BPEJ00-0](https://user-images.githubusercontent.com/57011422/193685616-cf6bf23f-0d7b-49b1-b65f-455b6e6c27ff.png)![pokeemerald-2](https://user-images.githubusercontent.com/57011422/193685624-5c56d894-d481-4b3e-b3e7-28c920f0bdbc.png) 

원래 10pt 폰트여서 넓혔던 건데, 
이제 기본 폰트를 좁은 것으로 바꿔놓았으니 다시 원래 사이즈로 돌려놔야 할 것 같습니다.

**Comment by koipkoi** [comment]
PR (#20)의 작업으로 남기겠습니다.
