### ISSUE TITLE
[그래픽]콘테스트 다음 N턴 그래픽

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-kr#22]
![pokeemerald-0](https://user-images.githubusercontent.com/57011422/194696786-f01e7509-6694-442e-bd1e-54a30d9289da.png)

다음 N턴 이 되도록 출력되어야 하는데 
로컬라이징 과정에서 Turn N으로 출력되게 바꾼 바람에 저렇게 된 것 같습니다. 

일단 이런 문제가 있었다는 것만 기록하기 위해서 올린 것이니 
나중에 원본 스크린샷도 함께 첨부하겠습니다

**Comment by koipkoi** [comment]
@poketony 숫자 부분의 위치를 중간으로 옮겨야 하는건가요?

**Comment by poketony** [comment]
네 맞습니다!
