### ISSUE TITLE
전당등록 축하멘트 위치 수정

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-kr#24]
![pokeemerald-0](https://github.com/koipkoi/pokeemerald-kr/assets/57011422/82ec0527-d4a9-4966-ae59-bd1c32ce5e54)

이번에 폰트를 수정해서 그런지 축하 멘트가 오른쪽으로 치우쳐져 있네요... 
멘트의 위치가 정중앙으로 오게 수정해 주시면 감사하겠습니다!
해당 문구는 
const u8 gText_WelcomeToHOF[] = _("전당등록을 축하합니다!"); 

입니다. (src/strings.c의 177행에 위치)

**Comment by koipkoi** [comment]
혹시 이전 폰트로 했을때도 이상하게 밀렸나요?
여러 계산을 해봐도 사진처럼은 절대로 나올 수 없습니다.

**Comment by poketony** [comment]
![pokeemerald-12](https://github.com/koipkoi/pokeemerald-kr/assets/57011422/4f84174a-7edf-4581-9ab7-ff6cf0d36a31)
확인해 보니 이전 버전에서도 치우친 상태로 떴었군요

**Comment by koipkoi** [comment]
@poketony 왼쪽 마진이 16px 정도 어떤 원인으로 더 들어간것으로 보이네요. 
폰트 변경의 문제로 보이진 않아서 다른 부분에서도 발생할 여지는 없어 보입니다.

일단 해당 화면은 자체적으로 16px를 줄이도록 하겠습니다.
