### ISSUE TITLE
기타 조사 처리

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-kr#25]
예를 들어 

혹시 “{STR_VAR_1}”{K_I}라고 들어본 적 있어? 

라는 대사가 있을 때, 조사 코드 앞에 붙는 ” 때문에 종성이 제대로 인식되지 않아 조사코드가 디폴트값으로만 출력되는 오류가 있습니다. 혹시 이 문제 해결 가능하신가요?

**Comment by koipkoi** [comment]
'"' 문자가 있으면 다른 문자가 존재하는 부분을 인식하게끔 작업은 가능합니다.

작업전에 비슷한 사례가 있는 번역을 먼저 참고해볼만한게 있을까요? 조사구분을 안하는 경우도 있기 때문에..

**Comment by poketony** [comment]
숫자 종성을 구분한 경우는 같은 시리즈 내에 있는데 ”까지 조사를 구분한 케이스를 찾지 못했네요... 
찾아보니 " 앞에 붙는 단어를 몇 가지로 고정시켜서 텍스트를 나눠버리곤 하네요(ORAS의 경우)

**Comment by koipkoi** [comment]
@poketony 숫자는 말씀주신대로 적용할게요. 그리고 조사코드 앞에 쌍따옴표 등이 있을 경우는 보류해두겠습니다.
