### ISSUE TITLE
나무열매 코드 출력 오류

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-kr#26]
![나무열매-0](https://github.com/koipkoi/pokeemerald-kr/assets/57011422/0c8e9432-8917-4b09-8470-7a6232b4442c)
.string "{PLAYER}{K_EUNNEUN} 푹신푹신한 흙에\n"
.string "{STR_VAR_1}열매를 심었다!$" 등의 대사에서 
{STR_VAR_1}에 들어가는 단어가 "XX 열매열매"가 됩니다. 

일단 고정 대사 쪽의 열매를 지우긴 했는데 이렇게 했을 경우
"XX 열매"가 되어 XX와 열매 사이에 한 칸 공백이 생기기 때문에, 이 공백을 없애고 싶습니다. 

{STR_VAR_1}에 "복슝열매", "오랭열매" 등의 단어가 들어가도록 수정해 주실 수 있나요? 
대사가 "봄이는 푹신푹신한 흙에 복슝열매를 심었다"가 되도록이요:)

해당 문구는

src 폴더 안의 item.c의 

void GetBerryCountString(u8 *dst, const u8 *berryName, u32 quantity)
{
    const u8 *berryString;
    u8 *txtPtr;

    if (quantity < 2)
        berryString = gText_Berry;
    else
        berryString = gText_Berries;

    txtPtr = StringCopy(dst, berryName);
    *txtPtr = CHAR_SPACE;
    StringCopy(txtPtr + 1, berryString); 

코드와 관련이 있는 것으로 보입니다.

**Comment by poketony** [comment]
StringCopy(txtPtr + 1, berryString); 에서 +1 부분을 지워 버리고 
StringCopy(txtPtr, berryString); 로 만드니 원하는 대로 작동하긴 하네요...?

**Comment by koipkoi** [comment]
```diff
txtPtr = StringCopy(dst, berryName);
-*txtPtr = CHAR_SPACE;
-StringCopy(txtPtr + 1, berryString);
+StringCopy(txtPtr, berryString);
```

@poketony 말씀주신 부분을 적용하면 원하시는 결과가 나오는게 맞습니다. 바로 윗부분도 삭제하는게 좋겠습니다.
