### ISSUE TITLE
콘테스트 그래픽 깨짐 현상

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-kr#29]
![misc origin](https://github.com/koipkoi/pokeemerald-kr/assets/57011422/773fbd11-6e79-4230-9118-e9d25032ee60)
![misc 이식](https://github.com/koipkoi/pokeemerald-kr/assets/57011422/891d7511-a944-4e48-bc4b-f22f5b56e305)
![오류pokeemerald-0](https://github.com/koipkoi/pokeemerald-kr/assets/57011422/d0eadf38-4fb2-47f9-aa87-6ab8b55ccf28)

원본 파일을 번역해서 적용하려고 했더니 이미지 팔레트가 깨진 것처럼 색이 불규칙적이고, 원본에서는 투명처리되었던 부분이 청록색으로 변해 화면을 덮어 아예 보이지 않게 되었습니다.(팔레트를 변경하지 않고 가능한 원본형식 그대로 적용했는데도 그렇습니다) 
변경사항을 적용하되 팔레트가 깨지지 않게 고쳐주실 수 있나요? 

나름 조사를 해봤는데, 
https://www.pokecommunity.com/showthread.php?t=471001의 마지막 답변과 관련이 있는 것 같습니다. (이미지가 회색음영이 아니라 아예 팔레트가 없어야 한다는 내용입니다) 

여담으로 png 이미지 수정 시에 Graphicgale에서 수정한 파일에 멋대로 bKGD 인덱스를 끼워넣어 경고 문구의 원인이 되는데, 이건 괜찮은 건지도 여쭙고 싶습니다.

**Comment by koipkoi** [comment]
rule 파일을 변경해야할듯한데 제가 여유될때 수정해놓겠습니다
.

**Comment by koipkoi** [comment]
PR (#30)에서 확인부탁드립니다.
