### ISSUE TITLE
교환 시 텍스트 위치 수정

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-kr#31]
![pokeemerald-0](https://github.com/koipkoi/pokeemerald-kr/assets/57011422/29f1760e-bb8c-4a6b-a725-8a4c07c73ada)

우측 하단의 "취소"가 중앙에서 벗어나 있습니다. 
수정 가능한 경우 수정해 주시면 감사하겠습니다. 
(그래픽이 깨지거나 하는 건 아니므로 수정이 어려울 경우 이슈를 그대로 닫아주시면 됩니다!)

**Comment by koipkoi** [comment]
UI 조정(#39)으로 옮기겠습니다.
