### ISSUE TITLE
메일 관련 오류

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-kr#36]
![스크린샷 2023-10-08 203024](https://github.com/koipkoi/pokeemerald-kr/assets/57011422/1fd2e991-a4e1-405c-9056-841128602665)

이지챗 단어에는 띄어쓰기가 들어가면 안 됨 + 
로부터{사람이름} -> {사람이름}(으)로부터로 변경

**Comment by koipkoi** [comment]
@poketony 띄어쓰기가 들어가면 안되는 예시가 '일지도 나이스'를 '일지도나이스'처럼 처리가 되어야 하는건가요?

**Comment by poketony** [comment]
아 띄어쓰기 부분은 그냥 이후에 단어를 새로 번역할 때 주의할 사항이라 메모용으로 적어 둔 겁니다... 괜히 적어놔서 혼동을 드렸네요 죄송합니다 

{사람이름} -> {사람이름}(으)로부터 부분만 해결해 주시면 됩니다!
