### ISSUE TITLE
벽지 바꾸기 코드 입력 오류

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-kr#8]
![K-026](https://user-images.githubusercontent.com/57011422/104860013-8f45fa00-596c-11eb-9f54-5528ac0570a9.png)

원래는 이렇게 떠야 코드 16자리를 모두 입력 가능한데 

아래처럼 8자리로 줄었더라고요

![pokeemerald_01](https://user-images.githubusercontent.com/57011422/104860065-cc11f100-596c-11eb-8fbe-d1f028adb630.png)

**Comment by koipkoi** [comment]
한글 키보드 구현에 따라서 표시되는 길이가 반으로 줄었습니다.
다른 코드를 입력하도록 하는 방법이나
해당 화면은 영문으로만 입력되도록 개조를 해야할 것 같습니다.

**Comment by poketony** [comment]
추가로 해당 화면에서 "아저씨에게 말을 알려주자" 부분의 폰트도 폭이 얇은 걸로 교체해야 할 것 같네요 
지금 당장 문제는 없지만 만약 더 긴 다른 대사가 있으면 짤릴 우려가 있어서

**Comment by koipkoi** [comment]
@poketony 다른 경우의 메시지도 함께 좁은폭으로 변경될수 있는데 같이 바뀌어도 문제가 없을까요?

**Comment by poketony** [comment]
@koipkoi 네, 아마 문제없을 거라고 생각합니다
